---
# Codecov configuration for Portguard
# See: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error
        branches:
          - main
    patch:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: false

ignore:
  - "cmd/"
  - "**/*_test.go"
  - "**/testdata/**"
  - "examples/"
  - "docs/"
  - "scripts/"
  - "build/"
  - "*.md"
  - "*.yml"
  - "*.yaml"

flags:
  unittests:
    paths:
      - internal/
    carryforward: true
    ignore:
      - "**/*_test.go"
